# Generated by Django 5.1.1 on 2024-10-04 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CorrectAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=255)),
                ('subject_contents', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='class',
            old_name='Class',
            new_name='class_name',
        ),
        migrations.RemoveField(
            model_name='class',
            name='School',
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sydney_participant', models.IntegerField()),
                ('sydney_percentile', models.DecimalField(decimal_places=2, max_digits=5)),
                ('correct_answer_percentage_per_class', models.DecimalField(decimal_places=2, max_digits=5)),
                ('correct_answer', models.CharField(max_length=50)),
                ('participant', models.IntegerField()),
                ('student_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category_id', models.IntegerField()),
                ('year_level_name', models.CharField(max_length=100)),
                ('answer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_answer', to='school.answer')),
                ('assessment_area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.assessmentarea')),
                ('award_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.award')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.class')),
                ('correct_answer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.correctanswer')),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.student')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.subject')),
            ],
        ),
    ]
