# Generated by Django 5.1.1 on 2024-10-04 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_answer_assessmentarea_award_correctanswer_student_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answers',
            new_name='answer',
        ),
    ]
