# Generated by Django 5.1.1 on 2024-10-04 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_rename_answers_answer_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='subject_contents',
            new_name='subject_score',
        ),
    ]
