# Generated by Django 5.1.1 on 2024-10-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_rename_subject_contents_subject_subject_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer',
            new_name='answers',
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_contents',
            field=models.CharField(default='Contents', max_length=255),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_score',
            field=models.CharField(default='75', max_length=255),
        ),
    ]
